[phases.setup]
nixPkgs = ["python311", "pip", "gcc", "pkg-config", "libffi"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements-production.txt"
]

[phases.build]
cmds = [
    "python -m compileall -b .",
    "find . -name '*.py' -delete"
]

[start]
cmd = "python railway_server.py" 