apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: medbillguard-agent-hpa
  namespace: medbillguard
  labels:
    app.kubernetes.io/name: medbillguard-agent
    app.kubernetes.io/component: autoscaling
    app.kubernetes.io/part-of: medbillguard-agent-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: medbillguard-agent
  minReplicas: 2
  maxReplicas: 20
  metrics:
    # CPU-based scaling
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Scale when CPU > 70%
    
    # Memory-based scaling  
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80  # Scale when Memory > 80%
    
    # Custom metric: HTTP requests per second
    - type: Pods
      pods:
        metric:
          name: medbillguard_analysis_duration_seconds
        target:
          type: AverageValue
          averageValue: "5"  # 5 seconds average analysis time
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
        - type: Percent
          value: 50  # Scale down by 50% of current replicas
          periodSeconds: 60
        - type: Pods
          value: 2  # Scale down by max 2 pods
          periodSeconds: 60
      selectPolicy: Min  # Use the policy that results in the smallest change
    
    scaleUp:
      stabilizationWindowSeconds: 60  # 1 minute
      policies:
        - type: Percent
          value: 100  # Scale up by 100% of current replicas
          periodSeconds: 60
        - type: Pods
          value: 4  # Scale up by max 4 pods
          periodSeconds: 60
      selectPolicy: Max  # Use the policy that results in the largest change

---
# Vertical Pod Autoscaler (VPA) for right-sizing resources
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: medbillguard-agent-vpa
  namespace: medbillguard
  labels:
    app.kubernetes.io/name: medbillguard-agent
    app.kubernetes.io/component: autoscaling
    app.kubernetes.io/part-of: medbillguard-agent-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: medbillguard-agent
  updatePolicy:
    updateMode: "Auto"  # Options: Off, Initial, Recreation, Auto
  resourcePolicy:
    containerPolicies:
      - containerName: medbillguard-agent
        minAllowed:
          cpu: 100m
          memory: 256Mi
        maxAllowed:
          cpu: 2000m
          memory: 4Gi
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsAndLimits 