apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medbillguardagent-data-pvc
  namespace: medbillguardagent
  labels:
    app.kubernetes.io/name: medbillguardagent
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Storage for LanceDB, cache, and temp files
  storageClassName: gp3  # AWS EBS GP3 for production
  volumeMode: Filesystem

---
# Separate PVC for vector database if needed
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medbillguardagent-vector-pvc
  namespace: medbillguardagent
  labels:
    app.kubernetes.io/name: medbillguardagent
    app.kubernetes.io/component: vector-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi  # Dedicated storage for vector embeddings
  storageClassName: gp3
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medbillguard-redis-pvc
  namespace: medbillguard
  labels:
    app.kubernetes.io/name: medbillguard-redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: medbillguard-agent-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd  # Adjust based on your cluster's storage classes

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medbillguard-postgres-pvc
  namespace: medbillguard
  labels:
    app.kubernetes.io/name: medbillguard-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: medbillguard-agent-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd  # Adjust based on your cluster's storage classes

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medbillguard-prometheus-pvc
  namespace: medbillguard
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: medbillguard-agent-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard  # Standard storage for monitoring data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medbillguard-grafana-pvc
  namespace: medbillguard
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: medbillguard-agent-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Standard storage for dashboards and config 