apiVersion: v1
kind: Secret
metadata:
  name: medbillguardagent-secrets
  namespace: medbillguardagent
  labels:
    app.kubernetes.io/name: medbillguardagent
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  # API Keys (Base64 encoded in production)
  OPENAI_API_KEY: "sk-placeholder-replace-with-actual-key"
  MISTRAL_API_KEY: "placeholder-mistral-key"
  
  # Database Connections
  VIVARAN_REDIS_URL: "redis://redis-service:6379/0"
  VIVARAN_NATS_URL: "nats://nats-service:4222"
  
  # S3/MinIO Storage
  VIVARAN_S3_ENDPOINT: "https://s3.amazonaws.com"
  VIVARAN_S3_ACCESS_KEY: "AKIA..."
  VIVARAN_S3_SECRET_KEY: "placeholder-s3-secret"
  VIVARAN_S3_BUCKET: "vivaranai-medbill-docs"
  VIVARAN_S3_REGION: "ap-south-1"
  
  # Vector Database
  LANCEDB_CONNECTION_STRING: "lancedb://lancedb-service:8001"
  
  # JWT Secrets
  JWT_SECRET_KEY: "super-secret-jwt-key-change-in-production"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_MINUTES: "60"
  
  # Encryption Keys
  DOCUMENT_ENCRYPTION_KEY: "32-char-encryption-key-change-me"
  
  # External API Keys
  CGHS_API_KEY: "placeholder-cghs-api-key"
  ESI_API_KEY: "placeholder-esi-api-key"
  NPPA_API_KEY: "placeholder-nppa-api-key"
  
  # Monitoring & Observability
  OTEL_EXPORTER_OTLP_HEADERS: "api-key=placeholder-observability-key"
  SENTRY_DSN: "https://placeholder@sentry.io/project-id"
  
  # Feature Flags Service
  UNLEASH_API_TOKEN: "development.unleash-insecure-api-token"
  UNLEASH_URL: "http://unleash-service:4242"
  
---
# Separate secret for database credentials
apiVersion: v1
kind: Secret
metadata:
  name: medbillguardagent-db-secrets
  namespace: medbillguardagent
  labels:
    app.kubernetes.io/name: medbillguardagent
    app.kubernetes.io/component: database
type: Opaque
stringData:
  # PostgreSQL for audit logs
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "medbillguard_audit"
  POSTGRES_USER: "medbillguard_user"
  POSTGRES_PASSWORD: "placeholder-postgres-password"
  
  # Redis Credentials
  REDIS_PASSWORD: "placeholder-redis-password" 